name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      xvfb:
        image: selenium/standalone-chrome
        options: >-
          --shm-size=1g
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build --if-present
      - name: Run unit tests
        run: npm test --if-present
  e2e:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with: { node-version: 18 }
      - name: Install
        run: npm ci
      - name: Start app
        run: npm run start & sleep 5
      - name: Run Cypress
        run: npx cypress run --headed --browser chrome || true
  lhci:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with: { node-version: 18 }
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build --if-present
      - name: Run Lighthouse CI
        run: npx @lhci/cli autorun --upload.target=temporary-public-storage || true
